modLoader="javafml"
loaderVersion="[3,]"
issueTrackerURL="https://github.com/neoforged/NeoForge/issues"
license="LGPL v2.1"

[[mods]]
    modId="neoforge"
    # We use the global NeoForge version
    version="${global.neoForgeVersion}"
    #updateJSONURL="https://maven.neoforged.net/releases/net/neoforged/forge/promotions_slim.json"
    displayName="NeoForge"
    credits="Anyone who has contributed on Github and supports our development"
    authors="The NeoForged Team"
    description='''
    NeoForge, a NEW broad compatibility API.
    '''
[[mods]]
    modId="youer"
    version="1.21"
    displayName="Youer"
    authors="MohistMC"
    description='''
    Youer, a server of Paper/Purpur and neoforge
    '''

[[mixins]]
    config = "neoforge.mixins.json"
